<?php

/**
 * Implements hook_entity_info_alter().
 */
function user_addressbook_commerce_entity_info_alter(&$info) {
  $info['user_address']['view modes']['user_addressbook_checkout'] = array(
    'label' => t('User addressbook for commerce'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_menu().
 */
function user_addressbook_commerce_menu() {
  $items = array();

  return $items;
}

/**
 * Implements hook_views_api().
 */
function user_addressbook_commerce_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'user_addressbook_commerce') . '/includes/views',
  );
}

/**
 * Implements hook_user_addressbook_address_type_info().
 */
function user_addressbook_commerce_user_addressbook_address_type_info() {
  $user_address_types = array();
  if (user_access('edit own user_address entities')) {
    foreach (commerce_customer_profile_types() as $type => $profile_type) {
      if ($profile_type['addressfield'] || isset($checkout_panes['customer_profile_' . $type])) {
        $user_address_types[$type] = array(
          'type' => $type, 
          'title' => $profile_type['name'], 
        );
      }
    }
  }

  return $user_address_types;
}

/**
 * Implements hook_entity_view().
 *
 * Adds the "edit", "delete" and "set as default" links to the customer profile.
 */
function user_addressbook_commerce_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'user_address' && $view_mode == 'user_addressbook_checkout') {
  }
}

/**
 * Implements hook_commerce_checkout_page_info().
 */
function user_addressbook_commerce_commerce_checkout_page_info() {
  $checkout_pages = array();

  $checkout_pages['addresses'] = array(
    'title' => t('Addresses'),
    'weight' => 0,
  );

  return $checkout_pages;
}

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function user_addressbook_commerce_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['user_addressbook'] = array(
    'title' => t('Addresses'),
    'base' => 'user_addressbook_commerce_checkout_pane',
    'file' => 'includes/user_addressbook_commerce.checkout_pane.inc',
    'page' => 'addresses',
    'weight' => 2,
    'review' => FALSE,
  );

  return $checkout_panes;
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 *
 * Use custom pane if the cart summary view has form elements.
 */
function user_addressbook_commerce_commerce_checkout_pane_info_alter(&$checkout_panes) {
  // Extract the View and display keys from the cart contents pane setting.
  if (user_access('edit own user_address entities')) {
    foreach (commerce_customer_profile_types() as $type => $profile_type) {
      if ($profile_type['addressfield'] || isset($checkout_panes['customer_profile_' . $type])) {
        $checkout_panes['customer_profile_' . $type]['enabled'] = FALSE;
        $checkout_panes['customer_profile_' . $type]['page'] = 'disabled';
        //$checkout_panes[$pane_id]['base'] = 'user_addressbook_commerce_customer_profile_pane';
      }
    }
  }
}

/**
 * Checkout pane callback: returns a customer profile edit form.
 */
function user_addressbook_commerce_customer_profile_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  global $user;
  $pane_form = array('#parents' => array($checkout_pane['pane_id']));

  // Extract the type of profile represented by this pane from its ID.
  $type = substr($checkout_pane['pane_id'], 17); // Removes 'customer_profile_'

  // Find the referenced profile using the related reference field...
  $wrapper = entity_metadata_wrapper('commerce_order', $order);
  $profile = NULL;

  // If the associated order field has been set...
  if ($field_name = variable_get('commerce_' . $checkout_pane['pane_id'] . '_field', '')) {
    // Check to ensure the specified profile reference field exists on the
    // current order type.
    if (!field_info_instance('commerce_order', $field_name, $order->type)) {
      return array();
    }

    $profile = $wrapper->{$field_name}->value();
  }
  else {
    // Or try the association stored in the order's data array if no field is set.
    if (!empty($order->data['profiles'][$checkout_pane['pane_id']])) {
      $profile = commerce_customer_profile_load($order->data['profiles'][$checkout_pane['pane_id']]);
    }
  }

  // Create a new profile of the specified type if it hasn't already been made.
  if (empty($profile)) {
    $profile = commerce_customer_profile_new($type, $order->uid);
  }

  // Add the entity context of the current cart order.
  $profile->entity_context = array(
    'entity_type' => 'commerce_order',
    'entity_id' => $order->order_id,
  );

  $pane_form['customer_profile'] = array(
    '#type' => 'value',
    '#value' => $profile,
  );

  $user_addressbook_view = '<div class="user-addressbook-wrapper">' . views_embed_view('user_addressbook_checkout', 'default', $user->uid, $type) . '</div>';

  $pane_form['user_addresses'] = array(
    '#markup' => $user_addressbook_view,
  );

  $pane_form['user_addresses_add_new'] = array(
    '#markup' => l('Add new', 'user-addressbook-checkout-add-new-profile/' . $type),
  );
 
  
  ///$pane_form += commerce_customer_profile_pane_checkout_form($form, &$form_state, $checkout_pane, $order);

  return $pane_form;

  // Add the field widgets for the profile.
  field_attach_form('commerce_customer_profile', $profile, $pane_form, $form_state);

  // If this checkout pane is configured to use values from a different
  // customer profile, add a checkbox to allow users to toggle this.
  if (variable_get('commerce_' . $checkout_pane['pane_id'] . '_profile_copy', FALSE)
    && $source_profile_type_name = variable_get('commerce_' . $checkout_pane['pane_id'] . '_profile_copy_source', NULL)) {
    // Load the default profile copy option from settings.
    $profile_copy_default = variable_get('commerce_' . $checkout_pane['pane_id'] . '_profile_copy_default', FALSE);

    // Make sure our profile type still exists..
    if ($source_profile_type = commerce_customer_profile_type_load($source_profile_type_name)) {
      $target_profile_type = commerce_customer_profile_type_load($profile->type);
      $pane_form['#prefix'] = '<div id="' . strtr($checkout_pane['pane_id'], '_', '-') . '-ajax-wrapper">';
      $pane_form['#suffix'] = '</div>';

      $pane_form['commerce_customer_profile_copy'] = array(
        '#type' => 'checkbox',
        '#title' => t('My %target is the same as my %source.', array('%target' => $target_profile_type['name'], '%source' => $source_profile_type['name'])),
        '#element_validate' => array('commerce_customer_profile_copy_validate'),
        '#default_value' => isset($order->data['profile_copy'][$checkout_pane['pane_id']]['status']) ? $order->data['profile_copy'][$checkout_pane['pane_id']]['status'] : $profile_copy_default,
        '#weight' => -30,
        '#ajax' => array(
          'callback' => 'commerce_customer_profile_copy_refresh',
          'wrapper' => strtr($checkout_pane['pane_id'], '_', '-') . '-ajax-wrapper',
        ),
        '#attached' => array(
          'css' => array(drupal_get_path('module', 'commerce_customer') . '/theme/commerce_customer.theme.css'),
        ),
        '#prefix' => '<div class="commerce-customer-profile-copy">',
        '#suffix' => '</div>',
      );

      // If the order data has reference to fields that were copied over, hide
      // them so we don't confuse the user by still allowing them to edit values.
      if (!empty($order->data['profile_copy'][$checkout_pane['pane_id']]['status']) && isset($order->data['profile_copy'][$checkout_pane['pane_id']]['elements'])) {
        foreach ($order->data['profile_copy'][$checkout_pane['pane_id']]['elements'] as $field_name => $field) {
          foreach ($field as $langcode => $items) {
            if (is_array($items)) {
              foreach ($items as $delta => $item) {
                if (!empty($pane_form[$field_name][$langcode][$delta])) {
                  $pane_form[$field_name][$langcode][$delta]['#access'] = FALSE;
                }
                elseif (!empty($pane_form[$field_name][$langcode])) {
                  $pane_form[$field_name][$langcode]['#access'] = FALSE;
                }
              }
            }
            else {
              $pane_form[$field_name][$langcode]['#access'] = FALSE;
            }
          }
        }
      }
      // If profile copy action has not been set and the default action TRUE.
      elseif (empty($order->data['profile_copy']) && $profile_copy_default) {
        // Get field names that will be copied from the source profile.
        foreach (field_info_instances('commerce_customer_profile', $source_profile_type['type']) as $field_name => $field) {
          // If the field exists on the destination profile then disable it.
          if (!empty($pane_form[$field_name])){
            $langcode = $pane_form[$field_name]['#language'];
            $pane_form[$field_name][$langcode]['#access'] = FALSE;
          }
        }
      }
    }
  }

  // Tweak the form to remove the fieldset from the address field if there
  // is only one on this profile.
  $addressfields = array();

  foreach (commerce_info_fields('addressfield', 'commerce_customer_profile') as $field_name => $field) {
    if (!empty($pane_form[$field_name]['#language'])) {
      $langcode = $pane_form[$field_name]['#language'];

      // Only consider this addressfield if it's represented on the form.
      if (!empty($pane_form[$field_name][$langcode])) {
        $addressfields[] = array($field_name, $langcode);
      }
    }
  }

  // Check to ensure only one addressfield was found on the form.
  if (count($addressfields) == 1) {
    list($field_name, $langcode) = array_shift($addressfields);

    foreach (element_children($pane_form[$field_name][$langcode]) as $delta) {
      // Don't mess with the "Add another item" button that could be present.
      if ($pane_form[$field_name][$langcode][$delta]['#type'] != 'submit') {
        $pane_form[$field_name][$langcode][$delta]['#type'] = 'container';
      }
    }
  }

  return $pane_form;
}
/**
 * Checkout pane callback: validates a customer profile edit form.
 */
function user_addressbook_commerce_customer_profile_pane_checkout_form_validate($form, &$form_state, $checkout_pane, $order) {
  dsm($form);
  dsm($form_state);

  return TRUE;
}

/**
 * Checkout pane callback: submits a customer profile edit form.
 */
function user_addressbook_commerce_customer_profile_pane_checkout_form_submit($form, &$form_state, $checkout_pane, $order) {
  dsm($form);
  dsm($form_state);
  /*
  $pane_id = $checkout_pane['pane_id'];

  // Check to ensure the specified profile reference field exists on the
  // current order type.
  $field_name = variable_get('commerce_' . $pane_id . '_field', '');

  if (!empty($field_name) && !field_info_instance('commerce_order', $field_name, $order->type)) {
    return;
  }

  // Ensure the profile is active.
  $profile = $form_state['values'][$pane_id]['customer_profile'];
  $profile->status = TRUE;

  // Set the profile's uid if it's being created at this time.
  if (empty($profile->profile_id)) {
    $profile->uid = $order->uid;
  }

  // Notify field widgets.
  field_attach_submit('commerce_customer_profile', $profile, $form[$checkout_pane['pane_id']], $form_state);

  // Save the profile.
  commerce_customer_profile_save($profile);

  // Store the profile ID for the related field as specified on the settings form.
  $wrapper = entity_metadata_wrapper('commerce_order', $order);

  if ($field_name = variable_get('commerce_' . $checkout_pane['pane_id'] . '_field', '')) {
    $wrapper->{$field_name} = $profile;
  }
  else {
    // Or make the association in the order's data array if no field was found.
    $order->data['profiles'][$checkout_pane['pane_id']] = $profile->profile_id;
  }
  */
}
